# Generated by Django 3.0.7 on 2020-06-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0002_auto_20200608_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpage',
            name='content',
            field=models.TextField(),
        ),
    ]
